{% set name = "finaletoolkit" %}
{% set version = "0.10.7" %}
{% set loess_version = "2.1.2" %}
{% set plotbin_version = "3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 4bd04c3be90f10eda39dcfa82c7f9ccaf653eb04ccf1161edc1f65060919a85b

  - url: https://files.pythonhosted.org/packages/a7/91/676f1839b94259e30ed85c962be6009c819e61b3fd29c64b34c0894e69b4/loess-{{ loess_version }}-py3-none-any.whl
    sha256: 105f12daa0fdff5185855ae57c2d3f25420fb30b475ae3f4078843a5c61699b9

  - url: https://files.pythonhosted.org/packages/1e/00/6b6b084717523a3bba465c42b7309849c9ee580d64f2baccf972bc3d462d/plotbin-{{ plotbin_version }}-py3-none-any.whl
    sha256: 3f95758fdf178572051ba7de0e30f3a2b7e4702f1d3c3a4bfc87a5cb232a0539

build:
  script:
    # Install the dependencies from the local wheel files.
    # We can install them all in one command. Pip will handle the order.
    - pip install loess-{{ loess_version }}-py3-none-any.whl plotbin-{{ plotbin_version }}-py3-none-any.whl --no-index --find-links .
    # Now install your package
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - finaletoolkit = finaletoolkit.cli.main_cli:main_cli
  # Increment the build number for the final recipe.
  number: 3

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9,<3.13
    - numpy
    - pysam
    - pybigwig
    - py2bit
    - tqdm
    - numba
    - scipy
    - pandas
    - statsmodels
    - matplotlib-base

test:
  imports:
    - finaletoolkit
    - loess
    - plotbin
  commands:
    - pip check
    - finaletoolkit --help
  requires:
    - pip

about:
  home: https://github.com/epifluidlab/FinaleToolkit
  summary: FinaleToolkit is a package and standalone program to extract fragmentation features of cell-free DNA from paired-end sequencing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Kudostoy0u